version: "3"
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  api:
    build: .
    command: bash -c "bundle install && bundle exec rake db:create && bundle exec puma -C config/puma.rb -e development"
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    volumes:
      - .:/app:cached
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build: ./client
    volumes:
      - ./client:/app:cached
      - frontend:/app/dist
    ports:
      - "3000:3000"
      - "34819:34819"
    depends_on:
      - api
    env_file:
      - ./.env
    command: sh -c "yarn && yarn start"
volumes:
  frontend:
  postgres_data: {}
networks:
  default:
    name: meli_default
